name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: mcr.microsoft.com/dotnet/core/aspnet:3.1
    
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Install node packages
      run: npm install
        
    - name: Build mdules
      run: npm run build
