name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: mcr.microsoft.com/dotnet/core/aspnet:3.1
    
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    - with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
